// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACr9-_J8DNR47AqDyUUb_Oj7Hs4-9m4xs',
    appId: '1:189199702337:web:370446b1fc20b5b91c29c0',
    messagingSenderId: '189199702337',
    projectId: 'eventlu-7065d',
    authDomain: 'eventlu-7065d.firebaseapp.com',
    storageBucket: 'eventlu-7065d.firebasestorage.app',
    measurementId: 'G-Z2RLYY23N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUK87zxbzzdrX2W-mdMEjPqAVFSnBd_zw',
    appId: '1:189199702337:android:317c47bf068849a31c29c0',
    messagingSenderId: '189199702337',
    projectId: 'eventlu-7065d',
    storageBucket: 'eventlu-7065d.firebasestorage.app',
  );
}
